#!/bin/zsh -e

mydir=${0:a:h}
cd $mydir/..

./bin/sitemap

UPDATED=$(git diff  --name-only  _config.yml  _site/sitemap.xml  _site/comments/)

if [ "$UPDATED" != "" ]; then
	echo '
	Some files have changed, please `git add` and `git commit`:

'
	git diff  _config.yml  _site/sitemap.xml  _site/comments/
	exit 1
fi
